[package]
name = "burntcookie"
version = "0.1.0"
authors = ["Ahseya <horrorho@users.noreply.github.com>"]

[dependencies]
clippy = {version = "*", optional = true}
byteorder = "0.5.3"
env_logger = "0.3.5"
log = "0.3.6"
getopts = "0.2.14"

[features]
default = []
